name: Cypress Parallel Tests

on: [pull_request]
permissions:
  actions: read        # Necessário para corrigir o erro Resource not accessible by integration (actions/workflow-runs#get-a-workflow-run)
  pull-requests: read  # Necessário para corrigir o erro 403 (Resource not accessible by integration)
  contents: read       # Geralmente necessária para fazer o checkout do código
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    environment: Staging
    # strategy:
    #   matrix:
    #     # run 3 copies of the current job in parallel
    #     recording-job: [1, 2, 3]
    container:
      image: cypress/browsers:24.21.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v7.4.6
        with:
          group: 'Chrome Tests'
          browser: chrome
          parallel: true
          record: true
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
          # pass the Cypress Cloud project ID as an environment variable or store it in the Cypress configuration file
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}